- name: ec2 launcher
  hosts: localhost
  connection: local
  tasks:
  - name: launching ec2
    ec2:
      aws_access_key: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
      aws_secret_key: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
      instance_type: t2.micro
      key_name: ansible
      image: ami-e24b7d9d
      region: us-east-1
      group: default
      count: 1
      vpc_subnet_id: subnet-d24211fe
      wait: yes
      assign_public_ip: yes
